version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./test_pagination_localhost-dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: test_pagination
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - network
  srv:
    depends_on:
      - postgres
    container_name: srv
    build:
      context: ./srv
    develop:
      watch:
        - action: sync
          path: ./srv/src
          target: /srv/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./srv/package.json
    environment:
      - APP_PG_URL=postgresql://user:password@postgres:5432/test_pagination?sslmode=disable
    ports:
      - "3000:3000"
    networks:
      - network
    command: npm run start:dev
  web:
    depends_on:
      - srv
    container_name: web
    build:
      context: ./web
    develop:
      watch:
        - action: sync
          path: ./web/src
          target: /web/src
          ignore:
            - node_modules/
        - action: rebuild
          path: ./web/package.json
    environment:
      - API_URL=http://srv:3000
    ports:
      - "3001:3001"
    networks:
      - network
    command: npm run dev
networks:
  network:
    driver: bridge
volumes:
  postgres_data:
